(function(root){
 'use strict';
 const beats=[
  {scene:1,mode:'photo',photo:'permission',layout:'intro',title:'Antes de estudar Direito, uma pessoa já vive entre normas.',camera:[1,0,0]},
  {scene:1,mode:'photo',photo:'permission',layout:'upper-left',title:'Peça antes de usar.',camera:[1.08,-1,-2]},
  {scene:1,mode:'photo',photo:'traffic',layout:'lower-right',title:'Pare no sinal vermelho.',from:[1.09,2,0],camera:[1.09,-2,0]},
  {scene:1,mode:'photo',photo:'access',layout:'lower-left',title:'Para entrar, identifique-se.',camera:[1.1,-2,-1]},
  {scene:1,mode:'photo',photo:'family',layout:'lower-left',title:'Se for se atrasar, avise.',camera:[1.07,-1,-1]},
  {scene:1,mode:'photo',photo:'religion',layout:'lower-left',title:'Durante a oração, faça silêncio.',from:[1.09,-1,0],camera:[1.02,0,0]},
  {scene:1,mode:'photo',photo:'contract',layout:'upper-left',title:'Cumpra o que foi combinado.',from:[1.02,0,0],camera:[1.1,0,-2]},
  {scene:2,mode:'composition',focus:'family',title:'Familiares.',layout:'lower-right'},
  {scene:2,mode:'composition',focus:'permission',title:'Sociais.',layout:'lower-left'},
  {scene:2,mode:'composition',focus:'religion',title:'Religiosas.',layout:'lower-left'},
  {scene:2,mode:'composition',focus:'traffic',title:'Jurídicas.',layout:'lower-left'},
  {scene:2,mode:'composition',title:'Essas referências podem se cruzar na mesma situação.',layout:'wide'},
  {scene:3,mode:'composition',title:'Todas essas regras são Direito?',layout:'wide'},
  {scene:3,mode:'composition',title:'Todas essas regras são Direito?',support:'Elas orientam condutas, mas não possuem necessariamente a mesma natureza.',layout:'wide'},
  {scene:4,mode:'video',title:'Um celular encontrado.',support:'Uma pessoa decide devolvê-lo.',layout:'video'},
  {scene:4,mode:'video',title:'Moral',support:'O que seria correto fazer?',layout:'video'},
  {scene:4,mode:'video',title:'Religião',support:'Que orientação uma crença religiosa pode oferecer?',layout:'video'},
  {scene:4,mode:'video',title:'Direito',support:'O que as normas jurídicas estabelecem para essa situação?',layout:'video'},
  {scene:4,mode:'video',title:'Uma mesma conduta.',support:'Pode ser orientada e avaliada por diferentes ordens normativas.',layout:'video'},
  {scene:5,mode:'synthesis',title:'Vivemos em um mundo de normas.',support:'Diferentes regras atravessam a mesma vida.',credit:'Norberto Bobbio',work:'Teoria da Norma Jurídica',layout:'wide'},
  {scene:6,mode:'photo',photo:'contract',title:'O que diferentes sociedades consideravam Direito?',layout:'bridge-intro',camera:[1,0,0]},
  {scene:6,mode:'bridge',title:'E quem tinha autoridade para dizer isso?',layout:'history'},
  {scene:7,mode:'epochs',state:'ladder',title:'É tentador contar a história como uma escada.',support:'Mas esta é uma leitura enganosa.',layout:'b2-bottom'},
  {scene:7,mode:'epochs',state:'open',title:'Essas sociedades não eram versões incompletas da nossa.',layout:'b2-bottom'},
  {scene:8,mode:'map',state:'scope',title:'O percurso escolhido.',support:'Mesopotâmia, Grécia, Roma, Europa medieval e Estado moderno.',layout:'b2-bottom'},
  {scene:8,mode:'map',state:'world',title:'Não é uma história universal do Direito.',support:'Experiências islâmicas, africanas, indianas, chinesas — e muitas outras — também têm suas histórias.',layout:'b2-bottom'},
  {scene:8,mode:'map',state:'brazil',title:'Por que este percurso?',support:'Estas tradições participaram da formação dos sistemas jurídicos europeus continentais e, por essa via, do Direito brasileiro.',layout:'b2-bottom'},
  {scene:9,mode:'context',state:'lens',title:'Podemos compreender esse mundo apenas com as categorias de hoje?',layout:'b2-question'},
  {scene:9,mode:'context',state:'understand',title:'Podemos compreender esse mundo apenas com as categorias de hoje?',support:'Precisamos conhecer seus problemas, instituições e crenças.',layout:'b2-question'},
  {scene:9,mode:'context',state:'name',title:'Evitar o presentismo.',support:'Compreender as sociedades do passado em seu próprio contexto, sem exigir delas as ideias e instituições contemporâneas.',layout:'b2-question'},
  {scene:10,mode:'photo',photo:'history',title:'O passado não é um rascunho imperfeito do presente.',layout:'b2-outro',from:[1,0,0],camera:[1.32,4.2,2.2],duration:12000,easing:'cubic-bezier(.2,0,.65,1)'},
  {scene:11,mode:'photo',photo:'history',title:'Mesopotâmia',support:'A justiça moldada por reis, escribas e deuses',layout:'b3-title',continueCamera:true,from:[1,0,0],camera:[1.32,4.2,2.2],duration:12000,easing:'cubic-bezier(.2,0,.65,1)'},
  {scene:12,mode:'ordalia',state:'play',title:'O rio podia participar do julgamento.',layout:'b3-opening'},
  {scene:13,mode:'ordalia',state:'question',title:'Isso era religião ou Direito?',layout:'b3-question'},
  {scene:13,mode:'ordalia',state:'question',title:'Isso era religião ou Direito?',support:'Naquela experiência, a autoridade do julgamento e a ordem religiosa podiam estar entrelaçadas.',layout:'b3-question',retain:true},
  {scene:14,mode:'mesopotamia',shot:'mari',title:'Ordália: uma prova perante o rio.',support:'Em certas controvérsias, buscava-se uma decisão atribuída aos deuses.',layout:'m-bottom',camera:[1.08,0,0],duration:6500},
  {scene:14,mode:'mesopotamia',shot:'mari',title:'Não era um gesto improvisado.',support:'Cartas de Mari registram deslocamento, acompanhamento e preparação ritual.',layout:'m-right',camera:[1.3,14,-1],duration:5200},
  {scene:14,mode:'mesopotamia',shot:'mari',title:'Sair em segurança podia ser um resultado favorável.',support:'O resultado era interpretado como arbitragem divina. Os detalhes da prova ainda são discutidos.',layout:'m-left',camera:[1.3,-14,-1],duration:6500},
  {scene:15,mode:'mesopotamia',shot:'stele',title:'“Código de Hammurabi”?',support:'Mesopotâmia · século XVIII a.C.',layout:'m-document',camera:[1,0,0],duration:0},
  {scene:15,mode:'mesopotamia',shot:'stele',title:'“Código de Hammurabi”?',support:'A expressão é tradicional. Não equivale a um código legislativo contemporâneo.',layout:'m-document',camera:[1,0,0],retain:true},
  {scene:15,mode:'mesopotamia',shot:'relief',title:'Hammurabi diante do deus Shamash.',support:'O relevo relaciona a autoridade régia à legitimação divina.',layout:'m-document',camera:[1.08,0,2],duration:6000},
  {scene:15,mode:'mesopotamia',shot:'writing',title:'Uma tradição escrita de decisões e soluções.',support:'Não podemos presumir sua aplicação como artigos de um código moderno.',layout:'m-left',camera:[1.15,0,-5],duration:6500},
  {scene:16,mode:'mesopotamia',shot:'scribes',title:'Os escribas não eram simples copistas.',layout:'m-bottom',camera:[1.04,0,0],duration:5000},
  {scene:16,mode:'mesopotamia',shot:'scribes',title:'Comparavam situações e formulavam soluções.',support:'Dominavam contratos-modelo, registros judiciais e documentos administrativos.',layout:'m-bottom',camera:[1.32,-3,-14],duration:6200},
  {scene:16,mode:'mesopotamia',shot:'tablet',title:'A escrita organizava relações concretas.',support:'Contrato de colheita · Sippar · cerca de 1640 a.C.',layout:'m-document',camera:[1,0,0],duration:0},
  {scene:16,mode:'mesopotamia',shot:'scribes',title:'O sagrado não excluía o raciocínio jurídico.',support:'Também havia técnica, procedimentos e conhecimento especializado.',layout:'m-bottom',camera:[1.16,0,-7],duration:6000},
  {scene:17,mode:'mesopotamia',shot:'synthesis',title:'De onde vinha a autoridade da decisão?',layout:'m-summary',camera:[1,0,0],reveal:0},
  {scene:17,mode:'mesopotamia',shot:'synthesis',title:'De onde vinha a autoridade da decisão?',layout:'m-summary',camera:[1.3,14,4],reveal:1,retain:true,duration:5400},
  {scene:17,mode:'mesopotamia',shot:'synthesis',title:'De onde vinha a autoridade da decisão?',layout:'m-summary',camera:[1.3,-14,-5],reveal:2,retain:true,duration:6500},
  {scene:17,mode:'mesopotamia',shot:'investiture',title:'De onde vinha a autoridade da decisão?',layout:'m-summary',camera:[1.5,12,-24],cameraCompact:[1.1,8,-20],reveal:3,retain:true,duration:6500},
  {scene:17,mode:'mesopotamia',shot:'synthesis',title:'De onde vinha a autoridade da decisão?',support:'Essas dimensões podiam entrelaçar-se na construção da justiça.',layout:'m-summary',camera:[1,0,0],reveal:3,retain:true}
 ];
 beats.push(
  {scene:18,mode:'grecia',shot:'family',title:'Grécia',support:'Quando a justiça se torna um problema',layout:'g-bottom',camera:[1,0,0],duration:0},
  {scene:19,mode:'grecia',shot:'family',title:'Uma família presa à vingança.',support:'Ifigênia e Orestes são filhos de Agamêmnon e Clitemnestra.',layout:'g-bottom',camera:[1.04,0,1],duration:4500},
  {scene:19,mode:'grecia',shot:'family',title:'Agamêmnon sacrifica a própria filha, Ifigênia.',layout:'g-bottom',camera:[1.62,29,30],duration:5500},
  {scene:19,mode:'grecia',shot:'family',title:'Clitemnestra mata Agamêmnon, seu marido.',support:'Entre os motivos está a vingança pela morte da filha.',layout:'g-bottom',camera:[1.15,-4,7],duration:6000},
  {scene:19,mode:'grecia',shot:'family',title:'Orestes mata a própria mãe para vingar o pai.',layout:'g-bottom',camera:[1.58,-29,28],duration:6000},
  {scene:20,mode:'grecia',shot:'pursuit',title:'Mas a vingança não encerra o conflito.',support:'As Erínias, divindades vingadoras, perseguem Orestes pelo assassinato da mãe.',layout:'g-bottom',camera:[1,0,0],duration:0},
  {scene:20,mode:'orestes',state:'play',title:'Cada morte exige outra?',layout:'g-video'},
  {scene:21,mode:'orestes',state:'question',title:'Um julgamento seria capaz de interromper esse ciclo de vingança?',layout:'g-question'},
  {scene:21,mode:'grecia',shot:'trial',title:'Um julgamento seria capaz de interromper esse ciclo de vingança?',support:'Na peça, Atena intervém: o conflito é submetido a um julgamento público.',layout:'g-question',retain:true,camera:[1,0,0],duration:0},
  {scene:21,mode:'grecia',shot:'trial',title:'A vingança deixa de ser a única resposta.',support:'Cidadãos são chamados a julgar o conflito.',layout:'g-bottom',camera:[1.48,-2,4],duration:6000},
  {scene:21,mode:'grecia',shot:'trial',title:'A intervenção de Atena continua decisiva.',support:'A deusa participa da transformação da justiça.',layout:'g-bottom',camera:[1.5,18,22],duration:5500},
  {scene:21,mode:'grecia',shot:'trial',title:'Não é uma simples passagem da religião para a razão.',support:'Deuses e seres humanos permanecem no mesmo universo de justiça.',layout:'g-bottom',camera:[1,0,0],duration:6500},
  {scene:21,mode:'grecia',shot:'trial',title:'Uma narrativa mítica, não um registro histórico.',support:'A Eumênides não relata a fundação factual dos tribunais atenienses.',layout:'g-bottom',camera:[1,0,0],duration:0},
  {scene:22,mode:'grecia',shot:'aristotle',title:'A filosofia acrescenta outra pergunta.',support:'O que torna uma decisão justa?',layout:'g-example',camera:[1.01,0,0],duration:6000},
  {scene:22,mode:'grecia',shot:'aristotle',title:'Aristóteles: justiça, igualdade e proporção.',support:'Quando tratar igualmente? Quando uma diferença justifica tratamento distinto?',layout:'g-example',camera:[1.03,0,1],duration:6000},
{scene:23,mode:'grecia',shot:'distribution',title:'Como distribuir bens e encargos?',layout:'g-example',camera:[1,0,0],duration:5000},
  {scene:23,mode:'grecia',shot:'distribution',title:'Como distribuir bens e encargos?',support:'Não basta repartir: é preciso definir um critério de proporção.',layout:'g-example',retain:true,camera:[1.08,0,0],duration:5500},
  {scene:23,mode:'grecia',shot:'distribution',title:'Justiça distributiva.',support:'A distribuição proporcional de bens e encargos.',layout:'g-example',camera:[1.08,0,0],duration:0},
  {scene:24,mode:'grecia',shot:'correction',title:'Um dano rompe o equilíbrio entre as partes.',support:'Neste exemplo, um vaso foi quebrado.',layout:'g-example',camera:[1,0,0],duration:5500},
  {scene:24,mode:'grecia',shot:'correction',title:'Como reparar esse desequilíbrio?',layout:'g-example',camera:[1.08,0,0],duration:5500},
  {scene:24,mode:'grecia',shot:'correction',title:'Como reparar esse desequilíbrio?',support:'A entrega de outro vaso representa, aqui, uma forma de reparação.',layout:'g-example',retain:true,camera:[1.08,0,0],duration:5000},
  {scene:24,mode:'grecia',shot:'correction',title:'Justiça corretiva.',support:'Restaurar o equilíbrio rompido na relação entre as pessoas.',layout:'g-example',camera:[1.08,0,0],duration:0},
  {scene:25,mode:'grecia',shot:'aristotle',title:'Não basta saber quem decide.',layout:'g-example',camera:[1.01,0,0],duration:5000},
  {scene:25,mode:'grecia',shot:'aristotle',title:'Não basta saber quem decide.',support:'Também importa perguntar: o que torna a decisão justa?',layout:'g-example',retain:true,camera:[1.01,0,0],duration:0}
 );
 beats.push(
  {scene:26,mode:'roma',shot:'coponio',title:'Roma',support:'Ius est ars boni et aequi — que “arte” é essa?',layout:'r-bottom',camera:[1,0,0],duration:0},
  {scene:26,mode:'roma',shot:'pontifices',title:'Em Roma, o Direito também convivia com ritos e religião.',layout:'r-bottom',camera:[1.015,.5,0],duration:7000},
  {scene:26,mode:'roma',shot:'pontifices',title:'Nos primeiros séculos de Roma, os pontífices — sacerdotes romanos — tiveram papel central na preservação e interpretação do saber jurídico.',layout:'r-bottom',camera:[1.015,.5,0],duration:0},
  {scene:26,mode:'roma',shot:'pontifices',title:'É nesse contexto que se desenvolve o raciocínio jurídico romano.',layout:'r-bottom',camera:[1.015,.5,0],duration:0},
  {scene:26,mode:'roma',state:'play',title:'Copônio registra sua vontade.',support:'Um filho ainda não nascido seria seu herdeiro.',layout:'r-bottom'},
  {scene:26,mode:'roma',state:'hold',title:'Mânio Cúrio seria o substituto.',support:'Caso o filho morresse antes de atingir a idade prevista.',layout:'r-bottom'},
  {scene:27,mode:'roma',shot:'ausencia',title:'Copônio morreu. O filho nunca nasceu.',layout:'r-bottom',camera:[1,0,0],duration:0},
  {scene:27,mode:'roma',shot:'ausencia',title:'Quem deveria herdar?',layout:'r-bottom',camera:[1,0,0],duration:0},
  {scene:27,mode:'roma',shot:'debate',title:'Quem deveria herdar?',support:'A causa Curiana: duas interpretações do mesmo testamento.',layout:'r-bottom',retain:true,camera:[1,0,0],duration:0},
  {scene:28,mode:'roma',shot:'debate',title:'Quinto Múcio Cévola',support:'A substituição dependia da condição prevista no testamento?',layout:'r-bottom',camera:[1.12,4,3],duration:5500},
  {scene:28,mode:'roma',shot:'debate',title:'Lúcio Licínio Crasso',support:'Copônio queria beneficiar Cúrio se não houvesse filho para herdar?',layout:'r-bottom',camera:[1.12,-4,3],duration:6500},
  {scene:28,mode:'roma',shot:'debate',title:'O mesmo testamento. Duas interpretações.',support:'Ambos mobilizavam argumentos jurídicos e retóricos.',layout:'r-bottom',camera:[1,0,0],duration:5500},
  {scene:29,mode:'roma',shot:'ausencia',title:'O problema jurídico não vem pronto.',support:'É preciso identificar quais fatos são relevantes.',layout:'r-bottom',camera:[1.04,0,1],duration:5000},
  {scene:29,mode:'roma',shot:'ausencia',title:'Os fatos conhecidos.',support:'Um filho previsto. Cúrio como substituto. O filho não nasceu.',layout:'r-bottom',camera:[1.04,0,1],duration:0},
  {scene:29,mode:'roma',shot:'debate',title:'Qual questão precisa ser respondida?',layout:'r-bottom',camera:[1,0,0],duration:0},
  {scene:29,mode:'roma',shot:'debate',title:'Qual questão precisa ser respondida?',support:'A substituição vale só na hipótese escrita ou também quando o filho não nasce?',layout:'r-bottom',retain:true,camera:[1,0,0],duration:0},
  {scene:29,mode:'roma',shot:'debate',title:'Construir o problema não é inventar fatos.',support:'É formular a questão jurídica sob a qual serão examinados.',layout:'r-bottom',camera:[1.04,0,1],duration:5000},
  {scene:29,mode:'roma',shot:'debate',title:'Interpretar exige apresentar razões.',support:'Não basta escolher uma resposta: é preciso sustentá-la.',layout:'r-bottom',camera:[1.04,0,1],duration:0},
  {scene:30,mode:'roma',shot:'debate',title:'Ius est ars boni et aequi.',support:'O Direito é a arte do bom e do equitativo.',credit:'Celso · fórmula posterior à causa Curiana, preservada no Digesto',layout:'r-bottom',camera:[1,0,0],duration:5500},
  {scene:30,mode:'roma',shot:'debate',title:'Que “arte” é essa?',layout:'r-bottom',camera:[1,0,0],duration:0},
  {scene:30,mode:'roma',shot:'debate',title:'Que “arte” é essa?',support:'Distinguir situações, interpretar e construir uma resposta jurídica.',layout:'r-bottom',retain:true,camera:[1,0,0],duration:0},
  {scene:30,mode:'roma',shot:'debate',title:'Arte não é improvisação.',support:'É um saber prático elaborado com distinções e argumentos.',layout:'r-bottom',camera:[1.04,0,1],duration:5000},
  {scene:31,mode:'roma',shot:'debate',title:'Uma resposta jurídica precisa ser construída — e sustentada pela argumentação.',layout:'r-bottom',camera:[1,0,0],duration:6000}
 );
 beats.push(
 {"scene":32,"mode":"medieval","shot":"philip","title":"Idade Média","support":"A disputa pelo poder de julgar","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":32,"mode":"medieval","shot":"philip","title":"Inglaterra. Século XII.","support":"Philip of Brois era um clérigo: um membro do clero.","layout":"md-focus","camera":[1.6,9.6,26],"duration":4500},
 {"scene":32,"mode":"medieval","shot":"philip","title":"Acusado de homicídio.","support":"Um tribunal eclesiástico o absolveu.","layout":"md-focus","camera":[1.6,9.6,26],"duration":0},
 {"scene":32,"mode":"medieval","shot":"philip","title":"O caso não terminou ali.","support":"Autoridades régias tentaram submetê-lo novamente à justiça secular.","layout":"md-focus","camera":[1.6,29,27],"duration":4500},
 {"scene":32,"mode":"medieval","shot":"philip","title":"Thomas Becket interveio.","support":"O arcebispo de Canterbury defendia a jurisdição eclesiástica sobre o clérigo.","layout":"md-focus","camera":[1.6,-29,3],"duration":6000},
 {"scene":33,"mode":"medieval","title":"Quem tinha o poder de julgá-lo?","layout":"md-bottom","camera":[1,0,0],"duration":0,"state":"play"},
 {"scene":33,"mode":"medieval","title":"Quem tinha o poder de julgá-lo?","support":"A disputa era também sobre os limites de cada autoridade.","layout":"md-bottom","camera":[1,0,0],"duration":0,"state":"hold","retain":true},
 {"scene":33,"mode":"medieval","title":"Jurisdição","support":"O poder reconhecido a uma autoridade para julgar conflitos.","layout":"md-bottom","camera":[1,0,0],"duration":0,"state":"hold"},
 {"scene":33,"mode":"medieval","title":"Ser clérigo fazia diferença.","support":"A condição de Philip importava para definir quem poderia julgá-lo.","layout":"md-bottom","camera":[1,0,0],"duration":0,"state":"hold"},
 {"scene":33,"mode":"medieval","title":"O poder de julgar não estava concentrado no rei.","support":"A Igreja era um dos centros de autoridade que também reivindicavam esse poder.","layout":"md-bottom","camera":[1,0,0],"duration":0,"state":"hold"},
 {"scene":34,"mode":"medieval","shot":"centros","title":"O olhar se amplia para outras experiências europeias.","support":"A Igreja e o rei não eram os únicos centros de autoridade.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":34,"mode":"medieval","shot":"centros","title":"Poderes senhoriais.","support":"Senhores podiam exercer autoridade sobre terras e pessoas.","layout":"md-bottom","camera":[1.22,7,5],"duration":6500},
 {"scene":34,"mode":"medieval","shot":"centros","title":"Cidades e corporações.","support":"Comunidades urbanas e associações de ofício também estabeleciam regras.","layout":"md-bottom","camera":[1.15,-4,0],"duration":6500},
 {"scene":34,"mode":"medieval","shot":"centros","title":"Não havia uma divisão única e fixa.","support":"Importavam o lugar, a época, a condição pessoal e o tipo de conflito.","layout":"md-bottom","camera":[1,0,0],"duration":6500},
 {"scene":34,"mode":"medieval","shot":"centros","title":"Pluralismo jurídico.","support":"Diferentes centros normativos e de julgamento podiam coexistir.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":34,"mode":"medieval","shot":"centros","title":"Pluralidade não é ausência de ordem.","support":"Nem todos esses centros estavam subordinados a um único poder político.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"Mas pluralidade não significava isolamento.","support":"Textos, métodos e saberes jurídicos também circulavam.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"Graciano. Por volta de 1140.","support":"A Igreja reunia textos de autoridades e épocas diferentes.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"Como conciliar textos que pareciam discordar?","layout":"md-bottom","camera":[1.1,0,-2],"duration":6000},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"Como conciliar textos que pareciam discordar?","support":"Comparar passagens, distinguir situações e buscar interpretações que as conciliassem.","layout":"md-bottom","camera":[1.1,0,-2],"duration":0,"retain":true},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"O Decreto de Graciano.","support":"Uma obra decisiva para o estudo e o ensino do direito canônico.","layout":"md-bottom","camera":[1.1,0,-2],"duration":0},
 {"scene":35,"mode":"medieval","shot":"graciano","title":"Direito canônico.","support":"O Direito da Igreja.","layout":"md-bottom","camera":[1.1,0,-2],"duration":0},
 {"scene":36,"mode":"medieval","shot":"aerea","title":"Bolonha: a cidade e seus espaços de estudo.","support":"A partir do século XII, o estudo do Direito romano ganha novo impulso.","layout":"md-aerial","camera":[1.36,-8,-5],"duration":11000,"from":[1.02,0,0]},
 {"scene":36,"mode":"medieval","shot":"aerea","title":"O saber jurídico também se aprende e se transmite.","support":"Professores e estudantes se reúnem em espaços integrados à cidade.","layout":"md-aerial","camera":[1.36,-8,-5],"duration":0},
 {"scene":36,"mode":"medieval","shot":"bolonha","title":"O texto romano volta a ser intensamente estudado.","support":"O Corpus Iuris Civilis: a compilação jurídica da época de Justiniano.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":36,"mode":"medieval","shot":"bolonha","title":"Ler, anotar, relacionar e interpretar.","support":"As glosas eram anotações que ajudavam a explicar os textos.","layout":"md-bottom","camera":[1.08,-2,0],"duration":6000},
 {"scene":36,"mode":"medieval","shot":"bolonha","title":"O trabalho não se limitava a copiar.","support":"Glosadores e, depois, comentadores elaboraram formas de compreender e aplicar os textos.","layout":"md-bottom","camera":[1.08,-2,0],"duration":0},
 {"scene":37,"mode":"medieval","shot":"map","title":"Ius commune","support":"Uma cultura jurídica erudita compartilhada na Europa continental.","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":37,"mode":"medieval","shot":"map","title":"Direito romano e direito canônico.","support":"Textos, conceitos e técnicas de interpretação compartilhados.","layout":"md-bottom","camera":[1,0,0],"duration":0,"mapState":"shared"},
 {"scene":37,"mode":"medieval","shot":"map","title":"E os direitos locais?","layout":"md-bottom","camera":[1,0,0],"duration":0},
 {"scene":37,"mode":"medieval","shot":"map","title":"E os direitos locais?","support":"Continuavam a existir: costumes e direitos particulares conviviam com essa cultura comum.","layout":"md-bottom","camera":[1,0,0],"duration":0,"retain":true,"mapState":"local"},
 {"scene":37,"mode":"medieval","shot":"map","title":"Não era um código único para toda a Europa.","support":"Ius commune também não significa common law.","layout":"md-bottom","camera":[1,0,0],"duration":0,"mapState":"local"},
 {"scene":37,"mode":"medieval","shot":"map","title":"Muitos direitos. Uma linguagem jurídica compartilhada.","support":"Pluralidade jurídica não significava isolamento.","layout":"md-bottom","camera":[1,0,0],"duration":0,"mapState":"local"}
 );
 const clamp=v=>Number.isFinite(Number(v))?Math.max(0,Math.min(beats.length-1,Math.round(Number(v)))):0;
 const step=(i,d)=>clamp(clamp(i)+d);
 const sceneStart=s=>Math.max(0,beats.findIndex(b=>b.scene===s));
 function action(e){
  if(e.repeat||e.metaKey||e.ctrlKey||e.altKey)return null;
  if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key))return 'next';
  if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key))return 'previous';
  return ({Home:'first',End:'last',h:'controls',H:'controls',Escape:'show',f:'fullscreen',F:'fullscreen',p:'play',P:'play',r:'replay',R:'replay'})[e.key]||null;
 }
 const model={beats,clamp,step,sceneStart,action};
 if(typeof module!=='undefined')module.exports=model;else root.JusLabModel=model;
})(typeof window!=='undefined'?window:globalThis);
